### ISSUE TITLE
Opening-from-inside button sometimes doesn't open the lock.

### ISSUE THREAD

**Issue by wprzyb** [HackerspaceKRK/zamek#1]
Since 2-3 weeks ago there are more and more situations when despite the button is pressed the lock responds with short beep and... that's all. In that cases rfid is needed to open the door from inside.

I tried now to record the bug, but now i can't reproduce it well. Works like a charm. But as i wrote - sometimes it doesn't.

**Comment by Teeed** [comment]
Confirmed

**Comment by KrystianD** [comment]
Interesting, since there's no beep on opening lock by button. Seems like wiring problem again. I'll check it today.

One question, is the beep always played when it is impossible to open lock by button?
